/**
 * Fixtures for the instance tests.
 *
 * Shaped from the generated DTOs rather than hand-typed objects, so a schema regeneration that
 * changes a field breaks the fixture — which is the point of having the generated types at all.
 */

import type { FitReport, Instance, Model } from '../../api/types';
import { emptyFormValues } from './values';
import type { InstanceFormValues } from './values';

export function makeModel(overrides: Partial<Model> = {}): Model {
  return {
    id: 'mdl_qwen',
    repo_id: 'bartowski/Qwen3-8B-GGUF',
    revision: 'main',
    primary_file: 'Qwen3-8B-Q4_K_M.gguf',
    quant_label: 'Q4_K_M',
    file_type: 'Q4_K_M',
    kind: 'text',
    state: 'ready',
    origin: 'hf',
    path: '/cache/models--bartowski--Qwen3-8B-GGUF/snapshots/abc/Qwen3-8B-Q4_K_M.gguf',
    snapshot_dir: '/cache/models--bartowski--Qwen3-8B-GGUF/snapshots/abc',
    root_id: 'root_1',
    root_path: '/cache',
    shard_count: 1,
    bytes_on_disk: 4_920_000_000,
    total_bytes: 4_920_000_000,
    has_vision: false,
    mmproj_auto: false,
    in_use_by: [],
    n_head_kv: [8],
    tensor_summary: {},
    gguf_parsed_at: '2026-08-01T00:00:00Z',
    tokenizer_model: 'gpt2',
    n_vocab: 151_936,
    n_layer: 36,
    created_at: '2026-08-01T00:00:00Z',
    updated_at: '2026-08-01T00:00:00Z',
    ...overrides,
  } as Model;
}

export function makeInstance(overrides: Partial<Instance> = {}): Instance {
  return {
    id: 'inst_qwen',
    name: 'qwen3-8b',
    display_name: 'Qwen3 8B',
    description: null,
    model_id: 'mdl_qwen',
    mmproj_model_id: null,
    draft_model_id: null,
    public_port: 8081,
    internal_port: 21001,
    auth_mode: 'token',
    autostart: true,
    restart_policy: 'on-failure',
    restart_max: 5,
    restart_window_sec: 600,
    flags: {
      ctx_size: 8192,
      n_gpu_layers: { mode: 'all' },
      parallel: 4,
      flash_attn: 'on',
      cache_type_k: 'q8_0',
      cache_type_v: 'q8_0',
      jinja: true,
      props_endpoint: true,
      slots_endpoint: true,
      metrics_endpoint: true,
    },
    extra_flags: '',
    config_hash: 'a'.repeat(64),
    desired_state: 'running',
    draft_validation: 'ok',
    unit_name: 'llamaman-instance@qwen3-8b.service',
    generation: 3,
    created_at: '2026-08-01T00:00:00Z',
    updated_at: '2026-08-20T00:00:00Z',
    deleted_at: null,
    status: {
      state: 'ready',
      systemd_active: 'active',
      systemd_sub: 'running',
      systemd_result: null,
      main_pid: 4242,
      exe_version_id: 'b10621-cuda-src',
      applied_config_hash: 'a'.repeat(64),
      ready_at: '2026-08-20T10:00:00Z',
      last_change_at: '2026-08-20T10:00:00Z',
      last_health_at: '2026-08-20T10:05:00Z',
      health_code: 200,
      slots_total: 4,
      slots_busy: 1,
      ctx_size: 8192,
      requests_served: 128,
      rss_bytes: 1_073_741_824,
      vram_bytes: 8_033_131_776,
      gpu_attribution: 'measured',
      last_exit_code: null,
      last_error: null,
    },
    restart_required: false,
    stale_version: false,
    inhibited: false,
    inhibit_reason: null,
    draft_unverified: false,
    ...overrides,
  } as Instance;
}

export function makeFitReport(overrides: Partial<FitReport> = {}): FitReport {
  return {
    inputs: {
      arch: 'qwen3',
      flash_attn: true,
      head_dim_k: 128,
      head_dim_v: 128,
      kv_ctx: 8192,
      n_batch: 2048,
      n_ctx: 8192,
      n_embd: 4096,
      n_expert: 0,
      n_expert_used: 0,
      n_ff: 12288,
      n_head: 32,
      n_head_kv: [8],
      n_layer: 36,
      n_layer_swa: 0,
      n_parallel: 4,
      n_ubatch: 512,
      n_vocab: 151_936,
      type_k: 'q8_0',
      type_v: 'q8_0',
    },
    weights_bytes: 4_920_000_000,
    weights_offloaded_bytes: 4_920_000_000,
    kv_bytes: 1_207_959_552,
    kv_offloaded_bytes: 1_207_959_552,
    kv_swa_bytes: 0,
    compute_bytes: 412_000_000,
    compute_act_bytes: 100_000_000,
    compute_attn_bytes: 100_000_000,
    compute_logits_bytes: 112_000_000,
    compute_moe_bytes: 100_000_000,
    backend_overhead_bytes: 419_430_400,
    margin_bytes: 1_073_741_824,
    margin_bytes_per_gpu: 1_073_741_824,
    reserve_bytes: 0,
    reserve_bytes_per_gpu: 0,
    required_vram_bytes: 8_033_131_776,
    spill_to_ram_bytes: 0,
    system_ram_free_bytes: 51_000_000_000,
    system_ram_known: true,
    vram_unknown: false,
    per_gpu: [
      {
        uuid: 'GPU-aaaa',
        index: 0,
        name: 'NVIDIA RTX 4090',
        free_bytes: 23_000_000_000,
        total_bytes: 25_769_803_776,
        assigned_bytes: 8_033_131_776,
        weights_bytes: 4_920_000_000,
        kv_bytes: 1_207_959_552,
        backend_overhead_bytes: 419_430_400,
        margin_bytes: 1_073_741_824,
        reserve_bytes: 0,
        extra_bytes: 0,
        short_by_bytes: 0,
        ok: true,
      },
    ],
    max_n_gpu_layers: 37,
    max_ctx_at_full_offload: 32_768,
    n_gpu_layers: 37,
    per_slot_ctx: 2048,
    recommendation: {
      n_gpu_layers: 37,
      flash_attn: true,
      type_k: 'q8_0',
      type_v: 'q8_0',
      reason: 'Everything fits with the safety margin intact.',
    },
    confidence: 'calibrated',
    calibration_samples: 12,
    calibration_clamped: false,
    notes: [],
    verdict: 'fits',
    ...overrides,
  } as FitReport;
}

/** A form that would save cleanly, for tests that then break exactly one thing. */
export function validFormValues(overrides: Partial<InstanceFormValues> = {}): InstanceFormValues {
  return {
    ...emptyFormValues(),
    name: 'qwen3-8b',
    model_id: 'mdl_qwen',
    public_port: '8081',
    internal_port: '21001',
    ctx_size: '8192',
    parallel: '4',
    ...overrides,
  };
}
