package cli

import (
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/jlbyh2o/llamaman/internal/selfupdate"
)

// `llamaman verify-release <dir>` — the release trust root, in one place
// (DESIGN sections 11.3, 12.1 step 3, 13 step 3 and 16.2 step 3).
//
// Two facts shape everything below.
//
// The first is that this is the ONLY signature check in the product, and it has
// to work with nothing installed. §13 step 3 runs it from a tarball that was
// unpacked seconds earlier on a host that has no gpg, no minisign and no
// network left to fetch one; §12.1 step 3 runs the same verification in process
// against a download the daemon staged. So the algorithm is ed25519 over the
// bytes of `checksums.txt` plus SHA-256 of the files that file names, and the
// only key material is compiled in. DESIGN section 14 declines a minisign
// library for exactly this reason: "ed25519 verification of a checksums file is
// ~40 lines against stdlib".
//
// The second is the ORDER §13 step 3 puts these in, which is deliberate and
// worth naming rather than discovering later. The installer runs `sha256sum -c`
// in the shell FIRST and only then execs the binary it just extracted to check
// the signature. The binary is therefore verifying its own provenance, which
// cannot detect a tarball that was malicious from the start — a hostile
// `llamaman` would simply print "ok". What it DOES detect, with no external
// tooling and no silent skip, is every failure that is actually plausible for a
// one-liner installer: a truncated or corrupted download, a mirror serving a
// stale release, an artifact swapped in transit for a genuine older signed
// build, and a `checksums.txt` edited anywhere between the release and the
// host. The residual — a compromised GitHub release — is closed by the fact
// that the SAME check runs in the self-update path (§12.1 step 3, §12.2 step 0)
// from a binary that was already trusted, and the swap actor re-runs it a third
// time across the privilege boundary rather than believing the stager.
//
// It creates nothing anywhere, opens no database and touches no state directory
// (§11.3), which is what makes it safe as one of the five root-invocable
// subcommands a CI test runs against an empty state directory owned by another
// uid.

// # ONE trust root, and this is not it
//
// The ed25519 release signing keys live in `internal/selfupdate/keys/*.pub` and
// are reached through `selfupdate.EmbeddedKeys()`. This file used to carry a
// SECOND pair, `ReleasePublicKeyB64`/`ReleaseNextPublicKeyB64`, with its own
// decoder and its own checksums parser — and nothing in the build, the tests or
// the docs asserted the two agreed.
//
// That is not a tidiness complaint. `install.sh` verifies a download by running
// `llamaman verify-release` (§13 step 3), while `POST /update/apply` and the
// root actor of §12.2 step 0 verify through the embedded set; release.yml's
// pre-build gate checked only the first. So the moment the real keypair was
// generated by the documented procedure, every release would have published
// green, `install.sh` would have verified fine, and **every self-update on every
// host would have refused its tarball at the signature step forever**, with a
// failure that reads like a corrupt download. The two implementations had
// already drifted in two places (hex signatures, and what to do about a `/` in a
// name), which is exactly the second-implementation hazard VerifyStaged's own
// doc comment warns about.
//
// There is now one key source, one signature decoder and one checksums parser,
// all in internal/selfupdate, and `releaseTrustRoot` below is the only thing
// this file adds: the refusal message for a checkout whose keypair has not been
// generated yet. `installer/README.md` documents the key files and release.yml
// derives its gate from them.

// ChecksumsFileName and ChecksumsSigFileName are the two fixed asset names the
// release publishes beside the tarballs (DESIGN section 16.2 step 3). They are
// fixed rather than versioned because `install.sh` fetches `checksums.txt`
// through `releases/latest/download/` BEFORE it knows the version — the asset
// names inside it are what tell the script which tag it is installing (D48,
// §13 step 2).
//
// They are aliases of the selfupdate constants rather than a second pair of
// literals, for the same reason the keys are: two names for one asset is two
// things that can drift.
const (
	ChecksumsFileName    = selfupdate.ChecksumsName
	ChecksumsSigFileName = selfupdate.SignatureName
)

// verifyReleaseFlags is the flag surface of this subcommand.
type verifyReleaseFlags struct {
	require stringList
	quiet   bool
}

// stringList is a repeatable string flag. --require names a file that MUST be
// covered by the signed checksums file and MUST verify; anything else listed in
// checksums.txt is verified when present and reported as skipped when it is
// not.
//
// The flag exists because a release lists both architectures' tarballs and
// `install.sh` downloads exactly one of them. Without it, "every file I have
// verifies" is trivially true for a directory containing no tarball at all, and
// the installer's hand-off would pass on a download that silently produced
// nothing.
type stringList []string

func (s *stringList) String() string { return strings.Join(*s, ",") }

func (s *stringList) Set(v string) error {
	if v == "" {
		return errors.New("empty value")
	}
	*s = append(*s, v)
	return nil
}

// VerifyRelease verifies a downloaded release directory against the embedded
// ed25519 public keys and the sha256 digests in its signed checksums file.
//
// The trust root is resolved HERE and passed down, so that this — the one
// production entry point — is the only thing that decides which keys count, and
// a test can drive the rest of the command with a keypair it owns rather than by
// mutating a package variable the self-update path would not have read.
func VerifyRelease(env Env, args []string) error {
	keys, err := releaseTrustRoot()
	if err != nil {
		fmt.Fprintf(env.Stderr, "llamaman verify-release: %v\n", err)
		return err
	}
	return verifyReleaseCommand(env, args, keys)
}

func verifyReleaseCommand(env Env, args []string, keys selfupdate.KeySet) error {
	var f verifyReleaseFlags

	fs := flag.NewFlagSet("verify-release", flag.ContinueOnError)
	fs.SetOutput(env.Stderr)
	fs.Var(&f.require, "require", "a file that must be listed in checksums.txt and must verify (repeatable)")
	fs.BoolVar(&f.quiet, "quiet", false, "print nothing on success")
	fs.Usage = func() {
		fmt.Fprintf(env.Stderr, "Usage: llamaman verify-release [flags] <dir>\n\n")
		fmt.Fprintf(env.Stderr, "Verifies %s in <dir> against the ed25519 release key compiled into\n", ChecksumsFileName)
		fmt.Fprintf(env.Stderr, "this binary (%s), then verifies the sha256 of every file it names\n", ChecksumsSigFileName)
		fmt.Fprintf(env.Stderr, "that is present in <dir>. Files listed but absent are reported as skipped;\n")
		fmt.Fprintf(env.Stderr, "use --require to insist that one is there.\n\n")
		fmt.Fprintf(env.Stderr, "It writes nothing, anywhere.\n\n")
		fs.PrintDefaults()
	}
	if err := fs.Parse(args); err != nil {
		return err
	}

	rest := fs.Args()
	if len(rest) != 1 {
		fmt.Fprintf(env.Stderr, "llamaman verify-release: exactly one directory is required\n")
		fs.Usage()
		return errors.New("verify-release: exactly one directory is required")
	}

	res, err := verifyRelease(rest[0], f.require, keys)
	if err != nil {
		fmt.Fprintf(env.Stderr, "llamaman verify-release: %v\n", err)
		return err
	}
	if !f.quiet {
		res.print(env)
	}
	return nil
}

// verifyResult is what a successful verification found, for the report.
type verifyResult struct {
	// Dir is the directory verified.
	Dir string
	// KeyIndex names WHICH compiled-in key verified the signature — 0 for the
	// current one, 1 for the next — so a rotation in progress is visible in the
	// output rather than silent. It is a report, never a decision.
	KeyIndex int
	// Verified and Skipped are file names from checksums.txt: present and
	// matching, and listed but absent.
	Verified []string
	Skipped  []string
}

func (r verifyResult) print(env Env) {
	var which string
	switch r.KeyIndex {
	case 0:
		which = "current"
	case 1:
		which = "next (rotation)"
	default:
		// Unreachable: the signature verified against SOME key in the set, and
		// the set is the current one and the next one. Naming the index rather
		// than guessing "current" is what keeps a future third key honest.
		which = fmt.Sprintf("#%d", r.KeyIndex)
	}
	fmt.Fprintf(env.Stdout, "llamaman: %s signature ok (%s release key)\n", ChecksumsFileName, which)
	for _, n := range r.Verified {
		fmt.Fprintf(env.Stdout, "llamaman: sha256 ok  %s\n", n)
	}
	for _, n := range r.Skipped {
		fmt.Fprintf(env.Stdout, "llamaman: skipped    %s (listed, not downloaded)\n", n)
	}
}

// verifyRelease is the whole check, separated from flag parsing so the table
// test can drive it directly — and taking its trust root as an argument, so a
// test supplies its own KeySet rather than mutating a package-level variable
// that the self-update path would not have been reading anyway.
func verifyRelease(dir string, required []string, keys selfupdate.KeySet) (verifyResult, error) {
	out := verifyResult{Dir: dir}

	// No key is a REFUSAL, never a skip, and it is checked here rather than only
	// at the entry point so the property holds for every caller. An empty KeySet
	// would otherwise fail one step later as a signature error, which reads like
	// a corrupt download rather than like a checkout whose keypair was never
	// generated.
	if len(keys) == 0 {
		return out, errors.New(noReleaseKey)
	}

	sums, err := os.ReadFile(filepath.Join(dir, ChecksumsFileName))
	if err != nil {
		return out, fmt.Errorf("reading %s: %w", ChecksumsFileName, err)
	}
	rawSig, err := os.ReadFile(filepath.Join(dir, ChecksumsSigFileName))
	if err != nil {
		return out, fmt.Errorf("reading %s: %w", ChecksumsSigFileName, err)
	}

	// The signature covers the bytes of checksums.txt EXACTLY as they were
	// signed — no trimming, no normalization. Every entry below is authentic
	// only because this passed. It is the same call the daemon and the root
	// actor make, against the same keys.
	if err := selfupdate.VerifyChecksums(sums, rawSig, keys); err != nil {
		return out, fmt.Errorf("%s does not verify against the release signing key compiled into "+
			"this binary (%s); the download is corrupt, truncated, or not the release it claims "+
			"to be: %w", ChecksumsFileName, selfupdate.KeyFingerprints(keys), err)
	}
	// Which key verified, so a rotation in progress is visible in the output
	// rather than silent. It is a report, not a decision: the verification above
	// already accepted the file.
	out.KeyIndex = keyIndex(sums, rawSig, keys)

	byName, err := selfupdate.ParseChecksums(sums)
	if err != nil {
		return out, err
	}

	// Every --require must be covered by the signature before anything is read
	// off disk: "the file I asked for is not in this release" is a different
	// answer from "the file I asked for does not match", and only the first one
	// can be given without opening anything.
	for _, name := range required {
		if _, ok := byName[name]; !ok {
			return out, fmt.Errorf("%s does not list %q; this is not the release that file came from", ChecksumsFileName, name)
		}
	}

	names := make([]string, 0, len(byName))
	for name := range byName {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		want := byName[name]
		got, err := selfupdate.FileSHA256(filepath.Join(dir, name))
		if errors.Is(err, os.ErrNotExist) {
			out.Skipped = append(out.Skipped, name)
			continue
		}
		if err != nil {
			return out, fmt.Errorf("hashing %s: %w", name, err)
		}
		if got != want {
			return out, fmt.Errorf("%s: sha256 mismatch\n  expected %s\n  actual   %s", name, want, got)
		}
		out.Verified = append(out.Verified, name)
	}

	verified := make(map[string]bool, len(out.Verified))
	for _, n := range out.Verified {
		verified[n] = true
	}
	for _, name := range required {
		if !verified[name] {
			return out, fmt.Errorf("%s is required but was not found in %s", name, dir)
		}
	}
	if len(out.Verified) == 0 {
		return out, fmt.Errorf("no file listed in %s is present in %s; nothing was verified", ChecksumsFileName, dir)
	}

	sort.Strings(out.Verified)
	sort.Strings(out.Skipped)
	return out, nil
}

// releaseTrustRoot is the ONE key source: the ed25519 public keys embedded from
// `internal/selfupdate/keys/*.pub`, which is exactly what `POST /update/apply`
// (§12.1 step 3) and the root swap actor (§12.2 step 0) verify against.
//
// A checkout whose release keypair has not been generated yet has no usable key,
// and that is a REFUSAL rather than a skip: it must fail loudly rather than
// install unverified bytes. The message names installer/README.md, which is
// where the procedure lives.
func releaseTrustRoot() (selfupdate.KeySet, error) {
	keys, err := selfupdate.EmbeddedKeys()
	if err != nil {
		return nil, fmt.Errorf("%s: %w", noReleaseKey, err)
	}
	return keys, nil
}

// noReleaseKey is that refusal's wording, in one place because two callers print
// it: the entry point, when the embedded set will not load at all, and
// verifyRelease, when it is handed an empty one.
const noReleaseKey = "no release signing key is compiled into this binary, so nothing can be " +
	"verified; see installer/README.md for generating the release keypair and committing its " +
	"public half to internal/selfupdate/keys/"

// keyIndex reports WHICH key verified — 0 for the current one, 1 for the next —
// so a rotation in progress shows up in the report. It runs only after
// VerifyChecksums has already accepted the file, so it decides nothing; -1 is
// returned for the case that cannot happen, rather than a misleading 0.
func keyIndex(sums, sig []byte, keys selfupdate.KeySet) int {
	for i := range keys {
		if selfupdate.VerifyChecksums(sums, sig, keys[i:i+1]) == nil {
			return i
		}
	}
	return -1
}
